version: '2'

#networks:
#  hanet: {}

services:
  web:
    image: dockercloud/hello-world
#  networks:
#     - hanet
  lb:
    image: dockercloud/haproxy
    links:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
      - 1936:1936
    environment:
      - BALANCE=roundrobin
      - DOCKER_TLS_VERIFY
      - DOCKER_HOST
      - DOCKER_CERT_PATH
#    networks:
#      - hanet