version: '3'

services:
  mailserver:
    image: tvial/docker-mailserver:latest
    hostname: mail
    domainname: domain.com
    environment:
    - ENABLE_SPAMASSASSIN=1
    - ENABLE_CLAMAV=1
    - ENABLE_FAIL2BAN=1
    - ENABLE_POSTGREY=1
    - ONE_DIR=1
    - DMS_DEBUG=0
    cap_add:
    - NET_ADMIN
    - SYS_PTRACE

  roundcube:
    image: roundcube/roundcubemail
    hostname: mailclient
    links:
      - mailserver
    ports:
      - 8080:80
    environment:
      - ROUNDCUBEMAIL_DEFAULT_HOST=mailserver
  
  telnet:
    image: ist346/ubuntu-16.04-base:latest
    hostname: telnet
    links:
      - mailserver
    entrypoint: ["tail", "-f", "/dev/null"]