version: '3'

services:
  mailserver:
    image: tvial/docker-mailserver:latest
    hostname: mail.mycompany.com
    volumes:
      - ./config/:/tmp/docker-mailserver/
    environment:
      - SSL_TYPE=self-signed
      - ENABLE_SPAMASSASSIN=1
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1
      - ENABLE_POSTGREY=0
      - ONE_DIR=1
      - DMS_DEBUG=0
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE

  roundcube:
    image: roundcube/roundcubemail
    hostname: mailclient
    links:
      - mailserver
    ports:
      - 8080:80
    environment:
      - ROUNDCUBEMAIL_DEFAULT_HOST=mailserver
      - ROUNDCUBEMAIL_DEFAULT_PORT=143
      - ROUNDCUBEMAIL_SMTP_SERVER=mailserver
      - ROUNDCUBEMAIL_SMTP_PORT=25
  
  telnet:
    image: ist346/ubuntu-16.04-base:latest
    hostname: telnet
    links:
      - mailserver
    entrypoint: ["tail", "-f", "/dev/null"]