version: '3'

services:

  nginx:
    build: nginx/.
    privileged: true
    ports:
      - 80:80
    networks:
      labJ:
        ipv4_address: 172.44.1.102

  client:
    image: ubuntu:16.04
    volumes:
      - ./home:/home
    networks:
      labJ:
        ipv4_address: 172.44.1.103
    entrypoint: ["tail", "-f", "/dev/null"]


networks:
  labJ:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.44.1.0/24