version: '3'

services:

  webserver:
    image: ist346/nginxfw:latest
    privileged: true
    hostname: webserver
    ports:
      - 80:80
    volumes:
      - ./nginx/website:/usr/share/nginx/html
    networks:
      lab_j:
        ipv4_address: 172.44.10.102

  client:
    image: ist346/hacker:latest
    hostname: client
    networks:
      lab_j:
        ipv4_address: 172.44.10.103
    entrypoint: ["tail", "-f", "/dev/null"]

  hacker:
    image: ist346/hacker:latest
    hostname: hacker
    depends_on:
      - webserver
    links:
      - webserver
    networks:
      lab_j:
        ipv4_address: 172.44.10.104
    entrypoint: ["/bin/bash", "/usr/bin/hack.sh"]


networks:
  lab_j:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.44.10.0/24