version: '3'
services:
  workstation:
    image: ist346/workstation:latest
    hostname: workstation
    privileged: true
    stdin_open: true
    tty: true
    networks: 
      - lab_b
    #entrypoint: /bin/bash
    
networks:
  lab_b:
    driver: bridge
    #enable_ipv6: true 
