version: '3'

services:

  webapp:
    build: flaskapp/.
    ports:
      - 8080
    environment:
      - SERVICE_PORTS=8080
    networks:
      - labG

  haproxy:
    image: dockercloud/haproxy
    links:
      - webapp
    environment:
#      - BALANCE=roundrobin
#      - BALANCE=leastconn
      - BALANCE=uri
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
      - 1936:1936
    networks:
      - labG


networks:
  labG:
    driver: bridge
    #enable_ipv6: true 
    ipam:
      driver: default
      config:
      -
        subnet: 172.44.1.0/24


