version: '3'
services:
  server:
    image: "ist346/server:latest"
#    container_name: server
    hostname: server
    privileged: true
    #stdin_open: true
    #tty: true
    networks: 
      - lab_c
    ports:
      - "22:22" # SSH
      - "80:80"
    # entrypoint: /usr/bin/docker-quickstart
  workstation:
    image: "ist346/ubuntu:latest"
 #   container_name: workstation
    hostname: workstation
    privileged: true
    stdin_open: true
    tty: true
    networks: 
      - lab_c
    entrypoint: /bin/bash
    
networks:
  lab_c:
    driver: bridge
    #enable_ipv6: true 
    ipam:
      driver: default
      config:
      -
        subnet: 172.44.3.0/24
