version: '3'
services:
  server:
    image: "ist346/lab01-server:latest"
    container_name: lab01_server
    hostname: server
    privileged: true
    #stdin_open: true
    #tty: true
    networks: 
      - lab01
    ports:
      - "22:22" # SSH
      - "80:80"
    # entrypoint: /usr/bin/docker-quickstart
  workstation:
    image: "ist346/ubuntu-16.04-base:latest"
    container_name: lab01_workstation
    hostname: workstation
    privileged: true
    stdin_open: true
    tty: true
    networks: 
      - lab01
    entrypoint: /bin/bash
    
networks:
  lab01:
    driver: bridge
    #enable_ipv6: true 
    ipam:
      driver: default
      config:
      -
        subnet: 172.44.1.0/24
