version: '3.3'

services:
  flask:
    build: flask-demo/.
    ports:
      - "80:8080"
    networks:
      - appnet
#    deploy:
#      mode: replicated
#      replicas: 1
networks:
  appnet:
#     driver: bridge
#    driver: overlay