version: '2.3'
services:
  squidex_mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    restart: unless-stopped
    networks:
      - lab_l

  squidex_server:
    image: "squidex/squidex:4.0.3"
    hostname: localhost 
    ports:
      - "80:80"
    networks:
      - lab_l
    environment:
      SQUIDEX_DOMAIN: localhost
      SQUIDEX_ADMINEMAIL: admin@example.com
      SQUIDEX_ADMINPASSWORD: MySquid123?
      SQUIDEX_FORCE_HTTPS: "false"
      SQUIDEX_PROTOCOL: http
      URLS__BASEURL: http://localhost
      EVENTSTORE__TYPE: MongoDB
      EVENTSTORE__MONGODB__CONFIGURATION: mongodb://squidex_mongodb
      STORE__MONGODB__CONFIGURATION: mongodb://squidex_mongodb
      IDENTITY__ADMINEMAIL: admin@example.com
      IDENTITY__ADMINPASSWORD: MySquid123?

    depends_on:
      - squidex_mongodb
    links:
      - squidex_mongodb
    restart: unless-stopped

  client:
    image: ist346/ubuntu:latest
    hostname: client
    links:
      - squidex_server
    entrypoint: ["tail", "-f", "/dev/null"]


networks:
  lab_l:
    driver: bridge
    #enable_ipv6: true 
    ipam:
      driver: default
      config:
      -
        subnet: 172.44.12.0/24