version: "3"

services:
  minio:
    image: minio/minio
    network_mode: bridge
    volumes:
      - ./data:/data
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: "server /data"