version: "3"

# minio 
services:
  minio:
    image: minio/minio
    hostname: server
#    volumes:
#      - ./data:/data
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: "server /data"
    networks: 
      labH:
        ipv4_address: 172.144.1.254
  client:
    image: minio/mc:edge
    hostname: client
    links: 
      - minio 
    entrypoint:
      - /bin/sh
    volumes:
      - ./files:/files
    networks: 
      labH:
        ipv4_address: 172.144.1.253
networks:
  labH:
    driver: bridge
    #enable_ipv6: true 
    ipam:
      driver: default
      config:
      -
        subnet: 172.144.1.0/24
