version: "3"

# minio 
services:
  minioserver:
    image: minio/minio:latest
    hostname: minioserver
#    volumes:
#      - ./data:/data
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: "server /data"
    networks: 
      lab_h:
        ipv4_address: 172.144.8.254
  client:
    image: minio/mc:latest
    hostname: client
    links: 
      - minioserver 
    entrypoint: ['tail', '-f', '/dev/null' ]
    volumes:
      - ./files:/files
    networks: 
      lab_h:
        ipv4_address: 172.144.8.253
networks:
  lab_h:
    driver: bridge
    #enable_ipv6: true 
    ipam:
      driver: default
      config:
      -
        subnet: 172.144.8.0/24
