version: "2.2"

services:
  ldap:
    # https://github.com/osixia/docker-openldap
    image: osixia/openldap:1.2.2
    environment:
      - LDAP_ORGANISATION="My Company"
      - LDAP_ADMIN_PASSWORD="JonSn0w"
      - LDAP_DOMAIN="my-company.com"

  server:
    build: server/.
    links:
      - ldap
    volumes:
      - ./smb.conf:/etc/samba/smb.conf
      - ./libnss-ldap.conf:/etc/libnss-ldap.conf
  
  client:
    build: client/.
    privileged: true # Need to add privileged mode so mount works!
    links:
      - server
      - ldap