version: '2'

services:
  mail:
    image: tvial/docker-mailserver:latest
    hostname: mail
    domainname: domain.com
    container_name: mail
    environment:
    - ENABLE_SPAMASSASSIN=1
    - ENABLE_CLAMAV=1
    - ENABLE_FAIL2BAN=1
    - ENABLE_POSTGREY=1
    - ONE_DIR=1
    - DMS_DEBUG=0
    cap_add:
    - NET_ADMIN
    - SYS_PTRACE

  roundcube:
    image: roundcube/roundcubemail
    hostname: mailclient
    links:
      - mail
    ports:
      - 8080:80
    environement:
      ROUNDCUBEMAIL_DEFAULT_HOST = mail
  
  telnet:
    image: ist346/ubuntu-16.04-base:latest
    hostname: telnet
    links:
      - mail
    entrypoint: ["tail", "-f", "/dev/null"]