version: "3"

services:
  iotsensorsimultor:
    image: mgarciap/iot-sensor-simulator
    links:
    - mosquitto
    environment:
      MOSCA_BROKER: mosquitto
    ports:
    - "9393:9393"  

  mosquitto:
    image: mgarciap/mosquitto
  
  sendmail:
    build: mail-server/.
    environment:
      SMTP_TO_EMAIL: YOUR_EMAIL_GOES_HERE
      SMTP_HOST: smtp.sendgrid.net
      SMTP_PORT: 587
      SMTP_USER: apikey
      SMTP_PASSWD: FROM_LAB_DOC
      SMTP_FROM_EMAIL: iot-test@syr.edu

  nodered:
    image: mgarciap/node-red
    links:
    - mosquitto
    - sendmail
    ports:
    - "1880:1880"
    