version: "3.1"

services:
  server:
    image: ist346/smbserver:latest
#    build: server/.
    hostname: server
  
  client:
    image: ist346/smbclient:latest 
#    build: client/.
    privileged: true # Need to add privileged mode so mount works!!!
    hostname: client
    links:
      - server
    depends_on:
      - server