version: '3'
services:
  nginx:
    image: "ist346/server:latest"
    hostname: webserver
    privileged: true
    #stdin_open: true
    #tty: true
    volumes:
      - ./2-tier/html/:/var/www/html/:rw
    networks: 
      - lab_f
    ports:
#      - "22:22" # SSH
      - "80:80"
    
networks:
  lab_f:
    driver: bridge
    #enable_ipv6: true 
    ipam:
      driver: default
      config:
      -
        subnet: 172.44.6.0/24
