version: '3.1'

services:

  nginx:
    #build: ./n-tier/nginx/.
    image: nginx:stable
    volumes: 
      - ./n-tier/nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: always
    ports:
      - "80:80"
    depends_on:
      - wordpress
    links: 
      - wordpress 
    networks: 
      lab_f:
        ipv4_address: 172.44.6.101

  wordpress:
    image: wordpress:5.7 
    hostname: wordpress
    restart: always
    depends_on:
      - mysql 
    links:
      - mysql
    ports:
      - 8080:80
    networks: 
      lab_f:
        ipv4_address: 172.44.6.102
    environment:
      WORDPRESS_DB_PASSWORD: example
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_NAME: wordpress_db
  mysql:
    image: mysql:5.7 
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wordpress 
      MYSQL_PASSWORD: example
    ports: 
      - 3306:3306
    networks: 
      lab_f:
        ipv4_address: 172.44.6.103

networks:
  lab_f:
    driver: bridge
    #enable_ipv6: true 
    ipam:
      driver: default
      config:
      -
        subnet: 172.44.6.0/24
