version: '3.1'

services:

  nginxn:
#    image: jwilder/nginx-proxy
    build: ./n-tier/nginx/.
    restart: always
    ports:
      - "80:80"
    links: 
      - wordpress 
    networks: 
      labF:
        ipv4_address: 172.44.1.101

  wordpress:
    image: wordpress # ist346/lab_f_wordpress:latest
    hostname: wordpress
    restart: always
    links:
      - mysql
    ports:
      - 8080:80
    networks: 
      labF:
        ipv4_address: 172.44.1.102
    environment:
      WORDPRESS_DB_PASSWORD: example

  mysql:
    image: mysql:5.7 # ist346/lab_f_mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports: 
      - 3306:3306
    networks: 
      labF:
        ipv4_address: 172.44.1.103

networks:
  labF:
    driver: bridge
    #enable_ipv6: true 
    ipam:
      driver: default
      config:
      -
        subnet: 172.44.1.0/24
