version: '3'

services:
  db:
    image: mysql:latest
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=SU2orange
      - MYSQL_DATABASE=django
      - MYSQL_USER=django_user
      - MYSQL_PASSWORD=SimplePassword
  nginx:
    image: nginx:alpine
    volumes:
      - ./n-tier//nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./n-tier/nginx/conf:/etc/nginx/conf.d
      - django_admin_static:/django_admin_static
    ports:
      - "80:80"
    depends_on:
      - web
  web:
    build: ./n-tier/.
    command: uwsgi --ini uwsgi.ini
    working_dir: /code/web
    volumes:
      - ./n-tier:/code
      - django_admin_static:/usr/local/lib/python3.6/site-packages/django/contrib/admin/static
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  django_admin_static: